[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/dht"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/torrent"

[[constraint]]
  name = "github.com/gortc/stun"
  version = "1.6.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/syncthing/syncthing"
  version = "0.14.46"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/bencode"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
